# Predicting the Success of Pirate Attacks
    
___

<img src = "lego_pirates.jpg" width = "1000" align = "left"/>

Image copyright: LEGO Group

## 1) Assignment description

You are provided with a dataset on vessels that have been attacked by pirates. Your task is to predict whether an attack is likely to be successful.

Clean and preprocess the data. This includes:
- Select features.
- One-hot encode categorical variables.
- How do you handle the date?
- Aggregate categories with few occurrences.

Compare the performance of different models. Run all of them, identify the best performing one and tune it. 

Finally, explain how it reaches a prediction.

**Note:** This repo took shape during my Data Science course at Propulsion Academy and was inspired by various in-class exercises. It gives a good overview of the content covered during the first month.

In [1]:
import pandas as pd

In [2]:
pirate_data = pd.read_csv(f"data/pirate_data.csv", index_col = 0)
pirate_data.head()

,DATETIME (LOCAL),DATETIME (UTC),DATE (LT),DATE (UTC),REGION,COUNTRY,INCIDENT TYPE,VESSEL TYPE,MAERSK?,VESSEL ACTIVITY LOCATION,LAT,LONG,TIMEZONE,TIME OF DAY,ATTACKS,ATTACK SUCCESS
1,2016-01-30 23:34:00,2016-01-30 22:34:00,2016-01-30,2016-01-30,WEST AFRICA,NIGERIA,"FAILED ATTACK, HIJACKING",CONTAINER SHIP,0,OFF SHORE,3.000000,6.250000,Africa/Lagos,EVENING,1,0
2,2016-01-29 23:40:00,2016-01-29 22:40:00,2016-01-29,2016-01-29,WEST AFRICA,NIGERIA,KIDNAP/RANSOM AT SEA,PRODUCT TANKER,0,OFF SHORE,2.500000,5.750000,Africa/Lagos,EVENING,1,1
3,2016-01-28 03:00:00,2016-01-28 02:00:00,2016-01-28,2016-01-28,SOUTH ASIA,INDIA,"FAILED ATTACK, ROBBERY",PRODUCT TANKER,0,ANCHORAGE,22.816667,70.116667,Asia/Kolkata,NIGHT,1,0
4,NaN,NaN,2016-01-27,2016-01-27,HORN OF AFRICA/ GULF OF ADEN,SOMALIA,SUSPICIOUS ACTIVITY AT SEA,NaN,0,OFF SHORE,13.998747,54.112792,Asia/Riyadh,UNKNOWN,1,0
5,2016-01-25 23:55:00,2016-01-25 22:55:00,2016-01-25,2016-01-25,SOUTH AMERICA,VENEZUELA,THEFT AT ANCHORAGE,GENERAL CARGO VESSEL,0,ANCHORAGE,10.267500,-63.432500,America/Caracas,EVENING,1,1